### ISSUE TITLE
Alarm doesn't go off on certain dates

### ISSUE THREAD

**Issue by winshipvarner** [dslackw/alarm#2]
I installed 'alarm' and it has been doing great until the month changed, but then I noticed that it no longer triggered an alarm when the time came. I looked in the source code, and here is what I found.

The alarm triggers when: begin == self.alarm_time

Here is the problematic code:

`                    if start_time[0] == '0':
                        begin = start_time[1:-3]`

Today, before hitting this if conditional, 'begin' was 04:20:23 and so was 'self.alarm_time'

After hitting this conditional, 'begin' was 4:20:23, whereas 'self.alarm_time' was 04:20:23

Because 4:20:23 does not equal 04:20:23, the alarm doesn't trigger.

I temporarily fixed the issue by commenting out these lines and recompiling the scripts, but I do not understand the code well enough to know what other problems this will lead to. Any help on this issue would be appreciated.

**Comment by dslackw** [comment]
Hi @winshipvarner,
Thanks for contribute. I found the solution when I remove two lines of code:
```
diff --git a/alarm/main.py b/alarm/main.py
index 68015e5..4e928dc 100755
--- a/alarm/main.py
+++ b/alarm/main.py
@@ -210,8 +210,8 @@ class ALARM(object):
                         "green") + start_time[3:] + self.color("endc"))
                     time.sleep(1)
                     begin = start_time[:-3]
-                    if start_time[0] == '0':
-                        begin = start_time[1:-3]
+                    # if start_time[0] == '0':
+                    #    begin = start_time[1:-3]
                     if begin == self.alarm_time:
                         self.position(6, 10, self.color(
                             "red") + start_time[3:-3] + self.color(
```
I don't remember why I added this two lines but never mind :)
Thanks again!

**Comment by winshipvarner** [comment]
Perfect, thanks mate!
